### ISSUE TITLE
Account Sign Up

### ISSUE THREAD

**Issue by sikhnationalarchives** [pwhipp/dsnac#13]
All users want to use the website to read books should sign up or create an account. They should be able to signup using Facebook, Twitter, Google or other social sites or able to create a simple local login account. All accounts should be verified. 

Here is a script that works with Django in order to for this functionality to work.

https://github.com/pennersr/django-allauth/blob/master/docs/overview.rst

**Comment by hqpr** [comment]
twitter auth is working, and something wrong with facebook and g+

**Comment by hqpr** [comment]
facebook auth fixed

**Comment by hqpr** [comment]
google + fixed.
task is done
