### ISSUE TITLE
Change Recent Scan look

### ISSUE THREAD

**Issue by sikhnationalarchives** [pwhipp/dsnac#23]
Is it possible to change the recent scan look:
![screen shot 2014-10-16 at 10 52 19 am](https://cloud.githubusercontent.com/assets/8286298/4664478/38a4e220-5544-11e4-97a6-a91c59be9c6c.png)

Instead of having two rows just have one long row with about 6 or 7 books and then have arrow buttons on both sides, pressing the arrow buttons reveals more books. the books keeps moving right/left or visa versa.

**Comment by hqpr** [comment]
done?
