### ISSUE TITLE
Social Media Sharing Button: basically user is reading a book and they want others to know about it, they just click on the facebook/twitter button and they can share that particular item

### ISSUE THREAD

**Issue by sikhnationalarchives** [pwhipp/dsnac#26]

**Comment by hqpr** [comment]
something like this ?
![hmuwvwe](https://cloud.githubusercontent.com/assets/3315477/6097021/41df0462-afb5-11e4-8eba-600145ee7ca2.png)

**Comment by sikhnationalarchives** [comment]
This looks great. Is it possible to add Google+ to it as well and same as facebook likes add the +button for the google likes as well. Otherwise it looks good to deploy.

**Comment by hqpr** [comment]
done
